export enum Actions {
  OPEN_CART = '@CART/OPEN_CART',
  CLOSE_CART = '@CART/CLOSE_CART',
  ADD_ITEM_TO_CART = '@CART/ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART = '@CART/REMOVE_ITEM_FROM_CART',
  ADD_ONE_UNIT_FOR_AN_ITEM_IN_CART = '@CART/ADD_ONE_UNIT_FOR_AN_ITEM_IN_CART',
  REMOVE_ONE_UNIT_FOR_AN_ITEM_IN_CART = '@CART/REMOVE_ONE_UNIT_FOR_AN_ITEM_IN_CART'
}

export interface Action {
  type: string
  payload: any
}
